name: My Workflow

on:
  push:
    branches:
      - main # Cambia esto al nombre de tu rama principal

permissions:
  contents: read

jobs:
  myJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Otros pasos de tu flujo de trabajo aquí...

      - name: Request Manual Approval
        if: always() # Este paso se ejecutará siempre, pero esperará aprobación manual
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pulls } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            });
            
            // El primer pull request abierto se utilizará para solicitar la aprobación
            if (pulls.length > 0) {
              await github.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pulls[0].number,
                event: 'APPROVE',
              });
            }
